// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNews.Api.Data;

#nullable disable

namespace MyNews.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251010192251_AddBGSites")]
    partial class AddBGSites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("Title", "SourceId")
                        .IsUnique();

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NewsItemId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("NewsTranslations");
                });

            modelBuilder.Entity("MyNews.Api.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dnevnik",
                            Url = "https://www.dnevnik.bg/rss/"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Novinite",
                            Url = "https://www.novinite.com/rss/news"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Capital",
                            Url = "https://www.capital.bg/rss/"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mediapool",
                            Url = "https://www.mediapool.bg/rss"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Actualno",
                            Url = "https://www.actualno.com/rss"
                        },
                        new
                        {
                            Id = 6,
                            Name = "24 Chasa",
                            Url = "https://www.24chasa.bg/rss_category/2/novini.html"
                        },
                        new
                        {
                            Id = 7,
                            Name = "BTA",
                            Url = "https://www.bta.bg/bg/rss/free"
                        },
                        new
                        {
                            Id = 8,
                            Name = "BNR",
                            Url = "https://bnr.bg/rss/"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SofiaGlobe",
                            Url = "http://feeds.feedburner.com/TheSofiaGlobe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pogled",
                            Url = "https://pogled.info/rss"
                        },
                        new
                        {
                            Id = 11,
                            Name = "BurgasNews",
                            Url = "https://www.burgasnews.com/feed"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gong",
                            Url = "https://gong.bg/rss"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Investor",
                            Url = "https://www.investor.bg/rss/news"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Vesti",
                            Url = "https://www.vesti.bg/rss"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Dnes",
                            Url = "https://www.dnes.bg/rss/news"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Blitz",
                            Url = "https://www.blitz.bg/rss"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Standart",
                            Url = "https://www.standartnews.com/rss"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Banker",
                            Url = "https://banker.bg/feed/"
                        },
                        new
                        {
                            Id = 1001,
                            Name = "Offnews - Политика",
                            Url = "https://feed.offnews.bg/rss/%D0%9F%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0_8"
                        },
                        new
                        {
                            Id = 1002,
                            Name = "Offnews - Общество",
                            Url = "https://feed.offnews.bg/rss/%D0%9E%D0%B1%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%BE_4"
                        },
                        new
                        {
                            Id = 1003,
                            Name = "Offnews - Икономика",
                            Url = "https://feed.offnews.bg/rss/%D0%98%D0%BA%D0%BE%D0%BD%D0%BE%D0%BC%D0%B8%D0%BA%D0%B0_59"
                        },
                        new
                        {
                            Id = 1004,
                            Name = "Offnews - Темида",
                            Url = "https://feed.offnews.bg/rss/%D0%A2%D0%B5%D0%BC%D0%B8%D0%B4%D0%B0_18762"
                        },
                        new
                        {
                            Id = 1005,
                            Name = "Offnews - Инциденти",
                            Url = "https://feed.offnews.bg/rss/%D0%98%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B8_6"
                        },
                        new
                        {
                            Id = 1006,
                            Name = "Offnews - Медии",
                            Url = "https://feed.offnews.bg/rss/%D0%9C%D0%B5%D0%B4%D0%B8%D0%B8_73"
                        },
                        new
                        {
                            Id = 1007,
                            Name = "Offnews - Свят",
                            Url = "https://feed.offnews.bg/rss/%D0%A1%D0%B2%D1%8F%D1%82%20_12"
                        },
                        new
                        {
                            Id = 1008,
                            Name = "Offnews - Туризъм",
                            Url = "https://feed.offnews.bg/rss/%D0%A2%D1%83%D1%80%D0%B8%D0%B7%D1%8A%D0%BC_75"
                        },
                        new
                        {
                            Id = 1009,
                            Name = "Offnews - Здраве",
                            Url = "https://feed.offnews.bg/rss/%D0%97%D0%B4%D1%80%D0%B0%D0%B2%D0%B5_18753"
                        },
                        new
                        {
                            Id = 25,
                            Name = "BBC News",
                            Url = "http://feeds.bbci.co.uk/news/rss.xml"
                        },
                        new
                        {
                            Id = 26,
                            Name = "CNN",
                            Url = "http://rss.cnn.com/rss/cnn_topstories.rss"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Reuters",
                            Url = "http://feeds.reuters.com/reuters/topNews"
                        },
                        new
                        {
                            Id = 28,
                            Name = "The New York Times",
                            Url = "http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
                        },
                        new
                        {
                            Id = 29,
                            Name = "The Guardian",
                            Url = "https://www.theguardian.com/world/rss"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Associated Press",
                            Url = "https://apnews.com/rss"
                        },
                        new
                        {
                            Id = 31,
                            Name = "NBC News",
                            Url = "http://feeds.nbcnews.com/nbcnews/public/news"
                        },
                        new
                        {
                            Id = 32,
                            Name = "USA Today",
                            Url = "http://rssfeeds.usatoday.com/usatoday-NewsTopStories"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Fox News",
                            Url = "http://feeds.foxnews.com/foxnews/latest"
                        },
                        new
                        {
                            Id = 34,
                            Name = "HuffPost",
                            Url = "https://www.huffpost.com/section/front-page/feed"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Bloomberg",
                            Url = "https://www.bloomberg.com/feed/podcast/etf-report.xml"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Yahoo News",
                            Url = "https://news.yahoo.com/rss/"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Politico",
                            Url = "https://www.politico.com/rss/politicopicks.xml"
                        },
                        new
                        {
                            Id = 38,
                            Name = "The Verge",
                            Url = "https://www.theverge.com/rss/index.xml"
                        },
                        new
                        {
                            Id = 39,
                            Name = "TechCrunch",
                            Url = "http://feeds.feedburner.com/TechCrunch/"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Wired",
                            Url = "https://www.wired.com/feed/rss"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Mashable",
                            Url = "http://feeds.mashable.com/Mashable"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Business Insider",
                            Url = "https://www.businessinsider.com/rss"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Bloomberg Technology",
                            Url = "https://www.bloomberg.com/feed/podcast/technology.xml"
                        },
                        new
                        {
                            Id = 44,
                            Name = "The Japan Times",
                            Url = "https://www.japantimes.co.jp/feed/"
                        },
                        new
                        {
                            Id = 45,
                            Name = "NHK World",
                            Url = "https://www3.nhk.or.jp/rss/news/cat0.xml"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Asahi Shimbun",
                            Url = "http://www.asahi.com/rss/asahi/newsheadlines.rdf"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Mainichi Shimbun",
                            Url = "https://mainichi.jp/rss/etc/flashnews.xml"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Kyodo News",
                            Url = "https://english.kyodonews.net/rss/news.xml"
                        },
                        new
                        {
                            Id = 49,
                            Name = "China Daily",
                            Url = "http://www.chinadaily.com.cn/rss/china_rss.xml"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Xinhua News",
                            Url = "http://www.xinhuanet.com/english/rss/worldrss.xml"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Global Times",
                            Url = "https://www.globaltimes.cn/rss/china.xml"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Caixin Global",
                            Url = "https://www.caixinglobal.com/feed/"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Korea Herald",
                            Url = "http://www.koreaherald.com/rss/018015000000/rssfeed.xml"
                        },
                        new
                        {
                            Id = 54,
                            Name = "The Times of India",
                            Url = "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Hindustan Times",
                            Url = "https://www.hindustantimes.com/rss/topnews/rssfeed.xml"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Der Spiegel",
                            Url = "https://www.spiegel.de/international/index.rss"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Die Zeit",
                            Url = "https://www.zeit.de/index.rss"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Frankfurter Allgemeine",
                            Url = "https://www.faz.net/rss/aktuell/"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Süddeutsche Zeitung",
                            Url = "https://www.sueddeutsche.de/rss"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Le Monde",
                            Url = "https://www.lemonde.fr/rss/une.xml"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Le Figaro",
                            Url = "http://www.lefigaro.fr/rss/figaro_actualites.xml"
                        },
                        new
                        {
                            Id = 62,
                            Name = "France 24",
                            Url = "https://www.france24.com/en/rss"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Corriere della Sera",
                            Url = "https://www.corriere.it/rss/homepage.xml"
                        },
                        new
                        {
                            Id = 64,
                            Name = "La Repubblica",
                            Url = "https://www.repubblica.it/rss/homepage/rss2.0.xml"
                        },
                        new
                        {
                            Id = 65,
                            Name = "El País",
                            Url = "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"
                        },
                        new
                        {
                            Id = 66,
                            Name = "El Mundo",
                            Url = "https://www.elmundo.es/rss/portada.xml"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Público",
                            Url = "https://feeds.publico.pt/rss/home"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Swiss Info",
                            Url = "https://www.swissinfo.ch/rss"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Scientific American",
                            Url = "https://www.scientificamerican.com/feed/"
                        },
                        new
                        {
                            Id = 70,
                            Name = "New Scientist",
                            Url = "https://www.newscientist.com/feed/home/"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Nature News (US)",
                            Url = "https://www.nature.com/news/rss"
                        },
                        new
                        {
                            Id = 72,
                            Name = "TechRadar",
                            Url = "https://www.techradar.com/rss"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Engadget",
                            Url = "https://www.engadget.com/rss.xml"
                        },
                        new
                        {
                            Id = 74,
                            Name = "PCMag",
                            Url = "https://www.pcmag.com/feeds/all-news"
                        },
                        new
                        {
                            Id = 75,
                            Name = "The Independent",
                            Url = "https://www.independent.co.uk/news/uk/rss"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Financial Times",
                            Url = "https://www.ft.com/?format=rss"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Daily Mail",
                            Url = "https://www.dailymail.co.uk/articles.rss"
                        },
                        new
                        {
                            Id = 78,
                            Name = "CBC News",
                            Url = "https://www.cbc.ca/cmlink/rss-canada"
                        },
                        new
                        {
                            Id = 79,
                            Name = "ABC News AU",
                            Url = "https://www.abc.net.au/news/feed/51120/rss.xml"
                        },
                        new
                        {
                            Id = 80,
                            Name = "SBS News",
                            Url = "https://www.sbs.com.au/news/feeds/rss/"
                        },
                        new
                        {
                            Id = 81,
                            Name = "NZ Herald",
                            Url = "https://www.nzherald.co.nz/rss/"
                        },
                        new
                        {
                            Id = 82,
                            Name = "RT News",
                            Url = "https://www.rt.com/rss/news/"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Globo",
                            Url = "https://g1.globo.com/rss/g1/"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Clarin",
                            Url = "https://www.clarin.com/rss/"
                        },
                        new
                        {
                            Id = 85,
                            Name = "AllAfrica",
                            Url = "https://allafrica.com/tools/headlines/rss/AllAfrica_headlines.xml"
                        },
                        new
                        {
                            Id = 86,
                            Name = "News24 South Africa",
                            Url = "https://www.news24.com/rss"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Al Jazeera",
                            Url = "https://www.aljazeera.com/xml/rss/all.xml"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Haaretz",
                            Url = "https://www.haaretz.com/cmlink/1.6401109"
                        },
                        new
                        {
                            Id = 89,
                            Name = "NASA RSS",
                            Url = "https://www.nasa.gov/rss/dyn/breaking_news.rss"
                        },
                        new
                        {
                            Id = 90,
                            Name = "ESA News",
                            Url = "https://www.esa.int/rssfeed"
                        },
                        new
                        {
                            Id = 91,
                            Name = "MIT Technology Review",
                            Url = "https://www.technologyreview.com/feed/"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Nature",
                            Url = "https://www.nature.com/subjects/news/rss"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Science Daily",
                            Url = "https://www.sciencedaily.com/rss/top/science.xml"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Ars Technica",
                            Url = "http://feeds.arstechnica.com/arstechnica/index"
                        },
                        new
                        {
                            Id = 95,
                            Name = "OpenAI Blog",
                            Url = "https://openai.com/blog/rss/"
                        },
                        new
                        {
                            Id = 96,
                            Name = "DeepMind Blog",
                            Url = "https://deepmind.com/blog/feed/rss"
                        },
                        new
                        {
                            Id = 97,
                            Name = "MIT CSAIL News",
                            Url = "https://www.csail.mit.edu/news/rss.xml"
                        },
                        new
                        {
                            Id = 98,
                            Name = "AI Trends",
                            Url = "https://www.aitrends.com/feed/"
                        },
                        new
                        {
                            Id = 99,
                            Name = "ESPN",
                            Url = "http://www.espn.com/espn/rss/news"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Sky Sports",
                            Url = "http://www.skysports.com/rss/12040"
                        },
                        new
                        {
                            Id = 101,
                            Name = "BBC Sport",
                            Url = "http://feeds.bbci.co.uk/sport/rss.xml?edition=uk"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Goal.com",
                            Url = "https://www.goal.com/feeds/en/news"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Bleacher Report",
                            Url = "https://bleacherreport.com/articles/feed"
                        },
                        new
                        {
                            Id = 104,
                            Name = "FIFA News",
                            Url = "https://www.fifa.com/rss/index.xml"
                        },
                        new
                        {
                            Id = 105,
                            Name = "UEFA News",
                            Url = "https://www.uefa.com/rssfeed"
                        });
                });

            modelBuilder.Entity("MyNews.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserNewsRead", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasClickedLink")
                        .HasColumnType("bit");

                    b.Property<bool>("HasClickedTitle")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "NewsItemId");

                    b.HasIndex("NewsItemId");

                    b.ToTable("UserNewsReads");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserSectionPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SectionType")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "SectionType");

                    b.ToTable("UserSectionPreferences");
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.HasOne("MyNews.Api.Models.Source", "Source")
                        .WithMany("NewsItems")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsTranslation", b =>
                {
                    b.HasOne("MyNews.Api.Models.NewsItem", "NewsItem")
                        .WithMany("Translations")
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserNewsRead", b =>
                {
                    b.HasOne("MyNews.Api.Models.NewsItem", "NewsItem")
                        .WithMany("UserReads")
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyNews.Api.Models.User", "User")
                        .WithMany("NewsReads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserSectionPreference", b =>
                {
                    b.HasOne("MyNews.Api.Models.User", "User")
                        .WithMany("SectionPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("UserReads");
                });

            modelBuilder.Entity("MyNews.Api.Models.Source", b =>
                {
                    b.Navigation("NewsItems");
                });

            modelBuilder.Entity("MyNews.Api.Models.User", b =>
                {
                    b.Navigation("NewsReads");

                    b.Navigation("SectionPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
