// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNews.Api.Data;

#nullable disable

namespace MyNews.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919120653_InitialCreateOfSources.")]
    partial class InitialCreateOfSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("NewsItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Example news content",
                            PublishedAt = new DateTime(2025, 8, 20, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Section = 5,
                            SourceId = 1,
                            Title = "First News"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Example news content 2",
                            PublishedAt = new DateTime(2025, 8, 10, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Section = 12,
                            SourceId = 2,
                            Title = "First News 2"
                        });
                });

            modelBuilder.Entity("MyNews.Api.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nova",
                            Section = 3,
                            Url = "https://nova.bg/"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BTV",
                            Section = 3,
                            Url = "https://btvnovinite.bg/"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dnevnik",
                            Section = 3,
                            Url = "https://www.dnevnik.bg/"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Offnews",
                            Section = 3,
                            Url = "https://offnews.bg/"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sportal",
                            Section = 5,
                            Url = "https://www.sportal.bg/"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gong",
                            Section = 5,
                            Url = "https://gong.bg/"
                        },
                        new
                        {
                            Id = 7,
                            Name = "24Chasa",
                            Section = 3,
                            Url = "https://www.24chasa.bg/"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dir.bg",
                            Section = 3,
                            Url = "https://www.dir.bg/"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Investor",
                            Section = 4,
                            Url = "https://www.investor.bg/"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Vesti.bg",
                            Section = 3,
                            Url = "https://www.vesti.bg/"
                        });
                });

            modelBuilder.Entity("MyNews.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.HasOne("MyNews.Api.Models.Source", "Source")
                        .WithMany("NewsItems")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MyNews.Api.Models.Source", b =>
                {
                    b.Navigation("NewsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
