// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNews.Api.Data;

#nullable disable

namespace MyNews.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106090826_AddSourceLanguageToNews")]
    partial class AddSourceLanguageToNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("Title", "SourceId")
                        .IsUnique();

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NewsItemId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("NewsTranslations");
                });

            modelBuilder.Entity("MyNews.Api.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dnevnik",
                            Url = "https://www.dnevnik.bg/rss/"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Capital",
                            Url = "https://www.capital.bg/rss/"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mediapool",
                            Url = "https://www.mediapool.bg/rss"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Actualno",
                            Url = "https://www.actualno.com/rss"
                        },
                        new
                        {
                            Id = 5,
                            Name = "BTA",
                            Url = "https://www.bta.bg/bg/rss/free"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SofiaGlobe",
                            Url = "http://feeds.feedburner.com/TheSofiaGlobe"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pogled",
                            Url = "https://pogled.info/rss"
                        },
                        new
                        {
                            Id = 8,
                            Name = "BurgasNews",
                            Url = "https://www.burgasnews.com/feed"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gong",
                            Url = "https://gong.bg/rss"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Investor",
                            Url = "https://www.investor.bg/rss/news"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Vesti",
                            Url = "https://www.vesti.bg/rss"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dnes",
                            Url = "https://www.dnes.bg/rss/news"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Blitz",
                            Url = "https://www.blitz.bg/rss"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Standart",
                            Url = "https://www.standartnews.com/rss"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Banker",
                            Url = "https://banker.bg/feed/"
                        },
                        new
                        {
                            Id = 16,
                            Name = "BBC News",
                            Url = "http://feeds.bbci.co.uk/news/rss.xml"
                        },
                        new
                        {
                            Id = 17,
                            Name = "BBC Technology",
                            Url = "http://feeds.bbci.co.uk/news/technology/rss.xml"
                        },
                        new
                        {
                            Id = 18,
                            Name = "NPR News",
                            Url = "https://feeds.npr.org/1001/rss.xml"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Nature – Latest Research",
                            Url = "https://www.nature.com/nature.rss"
                        },
                        new
                        {
                            Id = 20,
                            Name = "NY Times World",
                            Url = "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"
                        },
                        new
                        {
                            Id = 21,
                            Name = "NY Times Technology",
                            Url = "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"
                        },
                        new
                        {
                            Id = 22,
                            Name = "CNN",
                            Url = "http://rss.cnn.com/rss/cnn_topstories.rss"
                        },
                        new
                        {
                            Id = 23,
                            Name = "The New York Times",
                            Url = "http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
                        },
                        new
                        {
                            Id = 24,
                            Name = "NBC News",
                            Url = "http://feeds.nbcnews.com/nbcnews/public/news"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Fox News",
                            Url = "http://feeds.foxnews.com/foxnews/latest"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Wired",
                            Url = "https://www.wired.com/feed/rss"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Mashable",
                            Url = "http://feeds.mashable.com/Mashable"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Business Insider",
                            Url = "https://www.businessinsider.com/rss"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Yahoo News",
                            Url = "https://news.yahoo.com/rss/"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Politico",
                            Url = "https://www.politico.com/rss/politicopicks.xml"
                        },
                        new
                        {
                            Id = 31,
                            Name = "The Verge",
                            Url = "https://www.theverge.com/rss/index.xml"
                        },
                        new
                        {
                            Id = 32,
                            Name = "TechCrunch",
                            Url = "http://feeds.feedburner.com/TechCrunch/"
                        },
                        new
                        {
                            Id = 33,
                            Name = "The Japan Times",
                            Url = "https://www.japantimes.co.jp/feed/"
                        },
                        new
                        {
                            Id = 34,
                            Name = "NHK World",
                            Url = "https://www3.nhk.or.jp/rss/news/cat0.xml"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Asahi Shimbun",
                            Url = "http://www.asahi.com/rss/asahi/newsheadlines.rdf"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China Daily",
                            Url = "http://www.chinadaily.com.cn/rss/china_rss.xml"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Xinhua News",
                            Url = "http://www.xinhuanet.com/english/rss/worldrss.xml"
                        },
                        new
                        {
                            Id = 38,
                            Name = "SCMP (South China Morning Post)",
                            Url = "https://www.scmp.com/rss/91/feed"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Korea Herald - All Storeis",
                            Url = "https://www.koreaherald.com/rss/newsAll"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Korea Herald - National",
                            Url = "https://www.koreaherald.com/rss/kh_National"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Korea Herald - Business",
                            Url = "https://www.koreaherald.com/rss/kh_Business"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Korea Herald - Life & Culture",
                            Url = "https://www.koreaherald.com/rss/kh_LifenCulture"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Korea Herald - Sports",
                            Url = "https://www.koreaherald.com/rss/kh_Sports"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Korea Herald - World",
                            Url = "https://www.koreaherald.com/rss/kh_World"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Korea Times – Sports",
                            Url = "https://www.koreatimes.co.kr/www/rss/sports.xml"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Hindustan Times - US Sports",
                            Url = "https://www.hindustantimes.com/feeds/rss/sports/us-sports/rssfeed.xml"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Hindustan Times - Music",
                            Url = "https://www.hindustantimes.com/feeds/rss/entertainment/music/rssfeed.xml"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Hindustan Times - Football",
                            Url = "https://www.hindustantimes.com/feeds/rss/sports/football/rssfeed.xml"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Hindustan Times - Other Sports",
                            Url = "https://www.hindustantimes.com/feeds/rss/sports/others/rssfeed.xml"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Hindustan Times - Cinema",
                            Url = "https://www.hindustantimes.com/feeds/rss/htcity/cinema/rssfeed.xml"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Hindustan Times - Trips & Tours",
                            Url = "https://www.hindustantimes.com/feeds/rss/htcity/trips-tours/rssfeed.xml"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Hindustan Times - Tennis",
                            Url = "https://www.hindustantimes.com/feeds/rss/sports/tennis/rssfeed.xml"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Hindustan Times - Sports",
                            Url = "https://www.hindustantimes.com/feeds/rss/sports/rssfeed.xml"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Hindustan Times - Cricket",
                            Url = "https://www.hindustantimes.com/feeds/rss/cricket/rssfeed.xml"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Hindustan Times - Business",
                            Url = "https://www.hindustantimes.com/feeds/rss/business/rssfeed.xml"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Hindustan Times - News",
                            Url = "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Hindustan Times - Health",
                            Url = "https://www.hindustantimes.com/feeds/rss/lifestyle/health/rssfeed.xml"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Hindustan Times - Entertainment Others",
                            Url = "https://www.hindustantimes.com/feeds/rss/entertainment/others/rssfeed.xml"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Hindustan Times - Entertainment",
                            Url = "https://www.hindustantimes.com/feeds/rss/entertainment/rssfeed.xml"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Hindustan Times - Festivals",
                            Url = "https://www.hindustantimes.com/feeds/rss/lifestyle/festivals/rssfeed.xml"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Hindustan Times - Bollywood",
                            Url = "https://www.hindustantimes.com/feeds/rss/entertainment/bollywood/rssfeed.xml"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Hindustan Times - Hollywood",
                            Url = "https://www.hindustantimes.com/feeds/rss/entertainment/hollywood/rssfeed.xml"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Hindustan Times - Technology",
                            Url = "https://www.hindustantimes.com/feeds/rss/technology/rssfeed.xml"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Hindustan Times - Astrology",
                            Url = "https://www.hindustantimes.com/feeds/rss/astrology/rssfeed.xml"
                        },
                        new
                        {
                            Id = 66,
                            Name = "The Times of India",
                            Url = "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Der Spiegel",
                            Url = "https://www.spiegel.de/international/index.rss"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Frankfurter Allgemeine",
                            Url = "https://www.faz.net/rss/aktuell/"
                        },
                        new
                        {
                            Id = 69,
                            Name = "DW (Deutsche Welle)",
                            Url = "https://rss.dw.com/rdf/rss-en-all"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Sportschau",
                            Url = "https://www.sportschau.de/sportschauindex100~_type-rss.feed"
                        },
                        new
                        {
                            Id = 71,
                            Name = "FAZ Feuilleton",
                            Url = "https://www.faz.net/rss/aktuell/feuilleton/"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Musikexpress",
                            Url = "https://www.musikexpress.de/feed/"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Rolling Stone DE",
                            Url = "https://www.rollingstone.de/feed/"
                        },
                        new
                        {
                            Id = 74,
                            Name = "France 24",
                            Url = "https://www.france24.com/en/rss"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Le Monde",
                            Url = "https://www.lemonde.fr/rss/une.xml"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Le Figaro",
                            Url = "http://www.lefigaro.fr/rss/figaro_actualites.xml"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Le Monde Culture",
                            Url = "https://www.lemonde.fr/culture/rss_full.xml"
                        },
                        new
                        {
                            Id = 78,
                            Name = "France24 Culture",
                            Url = "https://www.france24.com/fr/culture/rss"
                        },
                        new
                        {
                            Id = 79,
                            Name = "RMC Sport - Football",
                            Url = "https://rmcsport.bfmtv.com/rss/football/"
                        },
                        new
                        {
                            Id = 80,
                            Name = "RMC Sport - Coupe du monde",
                            Url = "https://rmcsport.bfmtv.com/rss/football/coupe-du-monde/"
                        },
                        new
                        {
                            Id = 81,
                            Name = "RMC Sport - Football Euro",
                            Url = "https://rmcsport.bfmtv.com/rss/football/euro/"
                        },
                        new
                        {
                            Id = 82,
                            Name = "RMC Sport - Rugby",
                            Url = "https://rmcsport.bfmtv.com/rss/rugby/"
                        },
                        new
                        {
                            Id = 83,
                            Name = "RMC Sport - Rugby Coupe du monde",
                            Url = "https://rmcsport.bfmtv.com/rss/rugby/coupe-du-monde/"
                        },
                        new
                        {
                            Id = 84,
                            Name = "RMC Sport - Rugby Coupe d'Europe",
                            Url = "https://rmcsport.bfmtv.com/rss/rugby/coupe-d-europe/"
                        },
                        new
                        {
                            Id = 85,
                            Name = "RMC Sport - Tournoi des VI nations",
                            Url = "https://rmcsport.bfmtv.com/rss/rugby/tournoi-des-6-nations/"
                        },
                        new
                        {
                            Id = 86,
                            Name = "RMC Sport - Basket",
                            Url = "https://rmcsport.bfmtv.com/rss/basket/"
                        },
                        new
                        {
                            Id = 87,
                            Name = "RMC Sport - Basket NBA",
                            Url = "https://rmcsport.bfmtv.com/rss/basket/nba/"
                        },
                        new
                        {
                            Id = 88,
                            Name = "RMC Sport - Tennis",
                            Url = "https://rmcsport.bfmtv.com/rss/tennis/"
                        },
                        new
                        {
                            Id = 89,
                            Name = "RMC Sport - Tennis Roland Garros",
                            Url = "https://rmcsport.bfmtv.com/rss/tennis/roland-garros/"
                        },
                        new
                        {
                            Id = 90,
                            Name = "RMC Sport - Cyclisme",
                            Url = "https://rmcsport.bfmtv.com/rss/cyclisme/"
                        },
                        new
                        {
                            Id = 91,
                            Name = "RMC Sport - Cyclisme Tour de France",
                            Url = "https://rmcsport.bfmtv.com/rss/cyclisme/tour-de-france/"
                        },
                        new
                        {
                            Id = 92,
                            Name = "RMC Sport - Auto Moto Formule 1",
                            Url = "https://rmcsport.bfmtv.com/rss/auto-moto/f1/"
                        },
                        new
                        {
                            Id = 93,
                            Name = "RMC Sport - Jeux Olympiques",
                            Url = "https://rmcsport.bfmtv.com/rss/jeux-olympiques/"
                        },
                        new
                        {
                            Id = 94,
                            Name = "RMC Sport - Ligue des champions",
                            Url = "https://rmcsport.bfmtv.com/rss/football/ligue-des-champions/"
                        },
                        new
                        {
                            Id = 95,
                            Name = "RMC Sport - Ligue 1",
                            Url = "https://rmcsport.bfmtv.com/rss/football/ligue-1/"
                        },
                        new
                        {
                            Id = 96,
                            Name = "RMC Sport - Paris sportifs",
                            Url = "https://rmcsport.bfmtv.com/rss/pari-sportif/"
                        },
                        new
                        {
                            Id = 97,
                            Name = "RMC Sport - Golf",
                            Url = "https://rmcsport.bfmtv.com/rss/golf/"
                        },
                        new
                        {
                            Id = 98,
                            Name = "RMC Sport - Athlétisme",
                            Url = "https://rmcsport.bfmtv.com/rss/athletisme/"
                        },
                        new
                        {
                            Id = 99,
                            Name = "RMC Sport - Volleyball",
                            Url = "https://rmcsport.bfmtv.com/rss/volley/"
                        },
                        new
                        {
                            Id = 100,
                            Name = "RMC Sport - Auto moto",
                            Url = "https://rmcsport.bfmtv.com/rss/auto-moto/"
                        },
                        new
                        {
                            Id = 101,
                            Name = "RMC Sport - Sports de combat",
                            Url = "https://rmcsport.bfmtv.com/rss/sports-de-combat/"
                        },
                        new
                        {
                            Id = 102,
                            Name = "RMC Sport - Sports de combat Boxe",
                            Url = "https://rmcsport.bfmtv.com/rss/sports-de-combat/boxe/"
                        },
                        new
                        {
                            Id = 103,
                            Name = "RMC Sport - Voile",
                            Url = "https://rmcsport.bfmtv.com/rss/voile/"
                        },
                        new
                        {
                            Id = 104,
                            Name = "RMC Sport - Sport extrêmes",
                            Url = "https://rmcsport.bfmtv.com/rss/sports-extremes/"
                        },
                        new
                        {
                            Id = 105,
                            Name = "RMC Sport - Sport d'hiver",
                            Url = "https://rmcsport.bfmtv.com/rss/sports-d-hiver/"
                        },
                        new
                        {
                            Id = 106,
                            Name = "RMC Sport - Sport US",
                            Url = "https://rmcsport.bfmtv.com/rss/sport-us/"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Corriere della Sera",
                            Url = "https://www.corriere.it/rss/homepage.xml"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Corriere dello Sport",
                            Url = "https://www.corrieredellosport.it/rss/home"
                        },
                        new
                        {
                            Id = 109,
                            Name = "La Repubblica",
                            Url = "https://www.repubblica.it/rss/homepage/rss2.0.xml"
                        },
                        new
                        {
                            Id = 110,
                            Name = "ANSA",
                            Url = "https://www.ansa.it/sito/ansait_rss.xml"
                        },
                        new
                        {
                            Id = 111,
                            Name = "ANSA Cultura",
                            Url = "https://www.ansa.it/sito/notizie/cultura/cultura_rss.xml"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Gazzetta dello Sport",
                            Url = "https://www.gazzetta.it/rss/home.xml"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Repubblica Cultura",
                            Url = "https://www.repubblica.it/rss/cultura/rss2.0.xml"
                        },
                        new
                        {
                            Id = 114,
                            Name = "El País",
                            Url = "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"
                        },
                        new
                        {
                            Id = 115,
                            Name = "El Mundo",
                            Url = "https://www.elmundo.es/rss/portada.xml"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Marca",
                            Url = "https://e00-marca.uecdn.es/rss/portada.xml"
                        },
                        new
                        {
                            Id = 117,
                            Name = "AS - LaLiga EA Sports",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/futbol/subsection/primera/"
                        },
                        new
                        {
                            Id = 118,
                            Name = "AS - Champions League",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/futbol/subsection/champions/"
                        },
                        new
                        {
                            Id = 119,
                            Name = "AS - Europa League",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/futbol/subsection/uefa/"
                        },
                        new
                        {
                            Id = 120,
                            Name = "AS - Primera",
                            Url = "https://feeds.as.com/mrss-s/list/as/site/as.com/tag/primera_division_real_federacion_espanola_de_futbol_a/"
                        },
                        new
                        {
                            Id = 121,
                            Name = "AS - Segunda",
                            Url = "https://feeds.as.com/mrss-s/list/as/site/as.com/tag/segunda_division_real_federacion_espanola_futbol_a/"
                        },
                        new
                        {
                            Id = 122,
                            Name = "AS - Mundial",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/futbol/subsection/mundial/"
                        },
                        new
                        {
                            Id = 123,
                            Name = "AS - Eurocopa",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/futbol/subsection/eurocopa/"
                        },
                        new
                        {
                            Id = 124,
                            Name = "AS - Fórmula 1",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/motor/subsection/formula_1/"
                        },
                        new
                        {
                            Id = 125,
                            Name = "AS - Motociclismo",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/motor/subsection/motociclismo/"
                        },
                        new
                        {
                            Id = 126,
                            Name = "AS - Más Motor",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/motor/subsection/mas_motor/"
                        },
                        new
                        {
                            Id = 127,
                            Name = "AS - Copa del Rey",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/baloncesto/subsection/copa_del_rey/"
                        },
                        new
                        {
                            Id = 128,
                            Name = "AS - NBA",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/baloncesto/subsection/nba/"
                        },
                        new
                        {
                            Id = 129,
                            Name = "AS - Euroliga",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/baloncesto/subsection/euroliga/"
                        },
                        new
                        {
                            Id = 130,
                            Name = "AS - Eurocup",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/baloncesto/subsection/eurocup/"
                        },
                        new
                        {
                            Id = 131,
                            Name = "AS - Mundial",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/baloncesto/subsection/mundial_baloncesto/"
                        },
                        new
                        {
                            Id = 132,
                            Name = "AS - Open de Australia",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/tenis/subsection/open_australia/"
                        },
                        new
                        {
                            Id = 133,
                            Name = "AS - Roland Garros",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/tenis/subsection/roland_garros/"
                        },
                        new
                        {
                            Id = 134,
                            Name = "AS - Wimbledon",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/tenis/subsection/wimbledon/"
                        },
                        new
                        {
                            Id = 135,
                            Name = "AS - US Open",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/tenis/subsection/us_open/"
                        },
                        new
                        {
                            Id = 136,
                            Name = "AS - Más Tenis",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/tenis/subsection/mas_tenis/"
                        },
                        new
                        {
                            Id = 137,
                            Name = "AS - Masters 1000",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/tenis/subsection/masters_1000/"
                        },
                        new
                        {
                            Id = 138,
                            Name = "AS - Tour de Francia",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/ciclismo/subsection/tour_francia/"
                        },
                        new
                        {
                            Id = 139,
                            Name = "AS - Giro de Italia",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/ciclismo/subsection/giro_italia/"
                        },
                        new
                        {
                            Id = 140,
                            Name = "AS - Más Ciclismo",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/ciclismo/subsection/mas_ciclismo/"
                        },
                        new
                        {
                            Id = 141,
                            Name = "AS - Atletismo",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/masdeporte/subsection/atletismo/"
                        },
                        new
                        {
                            Id = 142,
                            Name = "AS - Polideportivo",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/masdeporte/subsection/polideportivo/"
                        },
                        new
                        {
                            Id = 143,
                            Name = "AS - Golf",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/masdeporte/subsection/golf/"
                        },
                        new
                        {
                            Id = 144,
                            Name = "AS - NFL",
                            Url = "https://feeds.as.com/mrss-s/pages/as/site/as.com/section/masdeporte/subsection/nfl/"
                        },
                        new
                        {
                            Id = 145,
                            Name = "AS - Boxeo",
                            Url = "https://feeds.as.com/mrss-s/list/as/site/as.com/tag/boxeo_a/"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Sport ES - Ciclismo",
                            Url = "https://www.sport.es/es/rss/ciclismo/rss.xml"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Sport ES - Hockey",
                            Url = "https://www.sport.es/es/rss/hockey/rss.xml"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Sport ES - Deporte Extremo",
                            Url = "https://www.sport.es/es/rss/deporte-extremo/rss.xml"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Sport ES - Fútbol América",
                            Url = "https://www.sport.es/es/rss/futbol-america/rss.xml"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Sport ES - Europa League",
                            Url = "https://www.sport.es/es/rss/europa-league/rss.xml"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Sport ES - Moto",
                            Url = "https://www.sport.es/es/rss/motor/rss.xml"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Sport ES - Golf",
                            Url = "https://www.sport.es/es/rss/golf/rss.xml"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Sport ES - Fútbol Internacional",
                            Url = "https://www.sport.es/es/rss/futbol-internacional/rss.xml"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Sport ES - NBA",
                            Url = "https://www.sport.es/es/rss/nba/rss.xml"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Sport ES - Atletismo",
                            Url = "https://www.sport.es/es/rss/atletismo/rss.xml"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Sport ES - Liga de Campeones",
                            Url = "https://www.sport.es/es/rss/champions-league/rss.xml"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Sport ES - Euroliga",
                            Url = "https://www.sport.es/es/rss/euroliga/rss.xml"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Mundo Deportivo",
                            Url = "https://www.mundodeportivo.com/rss/home.xml"
                        },
                        new
                        {
                            Id = 159,
                            Name = "ABC Cultura",
                            Url = "https://www.abc.es/rss/feeds/abc_Cultura.xml"
                        },
                        new
                        {
                            Id = 160,
                            Name = "20 Minutos Música",
                            Url = "https://www.20minutos.es/rss/musica/"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Jenesaispop",
                            Url = "https://jenesaispop.com/feed/"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Observador",
                            Url = "https://observador.pt/feed/"
                        },
                        new
                        {
                            Id = 163,
                            Name = "SwissInfo",
                            Url = "https://www.swissinfo.ch/eng/rss/rss"
                        },
                        new
                        {
                            Id = 164,
                            Name = "New Scientist",
                            Url = "https://www.newscientist.com/feed/home/"
                        },
                        new
                        {
                            Id = 165,
                            Name = "TechRadar",
                            Url = "https://www.techradar.com/rss"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Engadget",
                            Url = "https://www.engadget.com/rss.xml"
                        },
                        new
                        {
                            Id = 167,
                            Name = "NPR Top Stories",
                            Url = "https://feeds.npr.org/1001/rss.xml"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Washington Post World",
                            Url = "https://feeds.washingtonpost.com/rss/world"
                        },
                        new
                        {
                            Id = 169,
                            Name = "CNN Top Stories",
                            Url = "http://rss.cnn.com/rss/edition.rss"
                        },
                        new
                        {
                            Id = 170,
                            Name = "ESPN Top Headlines",
                            Url = "https://www.espn.com/espn/rss/news"
                        },
                        new
                        {
                            Id = 171,
                            Name = "CBS Sports",
                            Url = "https://www.cbssports.com/rss/headlines/"
                        },
                        new
                        {
                            Id = 172,
                            Name = "NPR Arts",
                            Url = "https://www.npr.org/rss/rss.php?id=1008"
                        },
                        new
                        {
                            Id = 173,
                            Name = "LA Times Entertainment",
                            Url = "https://www.latimes.com/entertainment-arts/rss2.0.xml"
                        },
                        new
                        {
                            Id = 174,
                            Name = "NYT Arts",
                            Url = "https://www.nytimes.com/services/xml/rss/nyt/Arts.xml"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Rolling Stone Music News",
                            Url = "https://www.rollingstone.com/music/music-news/feed/"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Billboard",
                            Url = "https://www.billboard.com/feed/"
                        },
                        new
                        {
                            Id = 177,
                            Name = "The Independent",
                            Url = "https://www.independent.co.uk/news/uk/rss"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Financial Times",
                            Url = "https://www.ft.com/?format=rss"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Daily Mail",
                            Url = "https://www.dailymail.co.uk/articles.rss"
                        },
                        new
                        {
                            Id = 180,
                            Name = "BBC World",
                            Url = "http://feeds.bbci.co.uk/news/world/rss.xml"
                        },
                        new
                        {
                            Id = 181,
                            Name = "BBC Sport",
                            Url = "http://feeds.bbci.co.uk/sport/rss.xml?edition=uk"
                        },
                        new
                        {
                            Id = 182,
                            Name = "BBC Entertainment & Arts",
                            Url = "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml"
                        },
                        new
                        {
                            Id = 183,
                            Name = "The Guardian World",
                            Url = "https://www.theguardian.com/world/rss"
                        },
                        new
                        {
                            Id = 184,
                            Name = "The Guardian Technology",
                            Url = "https://www.theguardian.com/uk/technology/rss"
                        },
                        new
                        {
                            Id = 185,
                            Name = "The Guardian Sport",
                            Url = "https://www.theguardian.com/uk/sport/rss"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Guardian Music",
                            Url = "https://www.theguardian.com/music/rss"
                        },
                        new
                        {
                            Id = 187,
                            Name = "GU Culture",
                            Url = "https://www.theguardian.com/uk/culture/rss"
                        },
                        new
                        {
                            Id = 188,
                            Name = "NME",
                            Url = "https://www.nme.com/rss"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Pitchfork News",
                            Url = "https://pitchfork.com/feed/feed-news/rss"
                        },
                        new
                        {
                            Id = 190,
                            Name = "CBC News",
                            Url = "https://www.cbc.ca/cmlink/rss-canada"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Global News",
                            Url = "https://globalnews.ca/feed/"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Globo",
                            Url = "https://g1.globo.com/rss/g1/"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Clarin",
                            Url = "https://www.clarin.com/rss/"
                        },
                        new
                        {
                            Id = 194,
                            Name = "NASA RSS",
                            Url = "https://www.nasa.gov/rss/dyn/breaking_news.rss"
                        },
                        new
                        {
                            Id = 195,
                            Name = "MIT News - Space",
                            Url = "https://news.mit.edu/topic/mitspace-rss.xml"
                        },
                        new
                        {
                            Id = 196,
                            Name = "ESA News",
                            Url = "https://www.esa.int/rssfeed/Our_Activities"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Space",
                            Url = "https://www.space.com/feeds/all"
                        },
                        new
                        {
                            Id = 198,
                            Name = "MIT Technology Review",
                            Url = "https://www.technologyreview.com/feed/"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Science Daily",
                            Url = "https://www.sciencedaily.com/rss/top/science.xml"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Ars Technica",
                            Url = "http://feeds.arstechnica.com/arstechnica/index"
                        },
                        new
                        {
                            Id = 202,
                            Name = "AI Trends",
                            Url = "https://www.aitrends.com/feed/"
                        },
                        new
                        {
                            Id = 203,
                            Name = "MIT News - AI",
                            Url = "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml"
                        },
                        new
                        {
                            Id = 204,
                            Name = "ESPN",
                            Url = "http://www.espn.com/espn/rss/news"
                        },
                        new
                        {
                            Id = 205,
                            Name = "BBC Sport",
                            Url = "http://feeds.bbci.co.uk/sport/rss.xml?edition=uk"
                        },
                        new
                        {
                            Id = 206,
                            Name = "The Economist",
                            Url = "https://www.economist.com/latest/rss.xml"
                        },
                        new
                        {
                            Id = 207,
                            Name = "The Washington Post",
                            Url = "https://feeds.washingtonpost.com/rss/politics"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Los Angeles Times",
                            Url = "https://www.latimes.com/world-nation/rss2.0.xml"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Financial Post (Canada)",
                            Url = "https://financialpost.com/feed/"
                        },
                        new
                        {
                            Id = 210,
                            Name = "The Hill",
                            Url = "https://thehill.com/feed/"
                        },
                        new
                        {
                            Id = 211,
                            Name = "UN News",
                            Url = "https://news.un.org/feed/subscribe/en/news/all/rss.xml"
                        },
                        new
                        {
                            Id = 212,
                            Name = "OECD Insights",
                            Url = "https://oecd-development-matters.org/feed/"
                        },
                        new
                        {
                            Id = 213,
                            Name = "UN Environment Programme (UNEP)",
                            Url = "https://www.unep.org/rss.xml"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Smithsonian Magazine",
                            Url = "https://www.smithsonianmag.com/rss/latest_articles/"
                        },
                        new
                        {
                            Id = 215,
                            Name = "LiveScience",
                            Url = "https://www.livescience.com/feeds/all"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Harvard Gazette",
                            Url = "https://news.harvard.edu/feed/"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Stanford News",
                            Url = "https://news.stanford.edu/feed/"
                        },
                        new
                        {
                            Id = 218,
                            Name = "MIT News - Latest News",
                            Url = "https://news.mit.edu/rss/feed"
                        },
                        new
                        {
                            Id = 219,
                            Name = "MIT News - Research",
                            Url = "https://news.mit.edu/rss/research"
                        },
                        new
                        {
                            Id = 220,
                            Name = "AAAS (Science Magazine) – News",
                            Url = "https://www.science.org/rss/news_current.xml"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Science Magazine",
                            Url = "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Cell Press News",
                            Url = "https://www.cell.com/cell/current.rss"
                        },
                        new
                        {
                            Id = 223,
                            Name = "ZDNet",
                            Url = "https://www.zdnet.com/news/rss.xml"
                        },
                        new
                        {
                            Id = 224,
                            Name = "MakeUseOf (MUO)",
                            Url = "https://www.makeuseof.com/feed/"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Android Authority",
                            Url = "https://www.androidauthority.com/feed/"
                        },
                        new
                        {
                            Id = 226,
                            Name = "IEEE Spectrum",
                            Url = "https://spectrum.ieee.org/rss/fulltext"
                        },
                        new
                        {
                            Id = 227,
                            Name = "W3C News",
                            Url = "https://www.w3.org/blog/news/feed/"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Mozilla Security Blog",
                            Url = "https://blog.mozilla.org/security/feed/"
                        },
                        new
                        {
                            Id = 229,
                            Name = "CNET",
                            Url = "https://www.cnet.com/rss/news/"
                        },
                        new
                        {
                            Id = 230,
                            Name = "The Economist – Finance & Economics",
                            Url = "https://www.economist.com/finance-and-economics/rss.xml"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Financial Times Alphaville",
                            Url = "https://ftalphaville.ft.com/feed/"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Fortune",
                            Url = "https://fortune.com/feed/"
                        },
                        new
                        {
                            Id = 233,
                            Name = "EU Observer",
                            Url = "https://euobserver.com/rss"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Politico EU",
                            Url = "https://www.politico.eu/feed/"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Euronews",
                            Url = "https://www.euronews.com/rss?level=theme&name=news"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Dagens Nyheter (Sweden)",
                            Url = "https://www.dn.se/rss/"
                        },
                        new
                        {
                            Id = 237,
                            Name = "NRK Norway",
                            Url = "https://www.nrk.no/toppsaker.rss"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Aftenposten (Norway)",
                            Url = "https://www.aftenposten.no/rss"
                        },
                        new
                        {
                            Id = 239,
                            Name = "The Local Sweden",
                            Url = "https://www.thelocal.se/feeds/rss.php"
                        },
                        new
                        {
                            Id = 240,
                            Name = "The Jerusalem Post",
                            Url = "https://www.jpost.com/Rss/RssFeedsHeadlines.aspx"
                        },
                        new
                        {
                            Id = 241,
                            Name = "Arab News",
                            Url = "https://www.arabnews.com/rss.xml"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Al Jazeera",
                            Url = "https://www.aljazeera.com/xml/rss/all.xml"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Mail & Guardian (South Africa)",
                            Url = "https://mg.co.za/feed/"
                        },
                        new
                        {
                            Id = 244,
                            Name = "BBC Africa",
                            Url = "http://feeds.bbci.co.uk/news/world/africa/rss.xml"
                        },
                        new
                        {
                            Id = 245,
                            Name = "The Age",
                            Url = "https://www.theage.com.au/rss/feed.xml"
                        },
                        new
                        {
                            Id = 246,
                            Name = "The Sydney Morning Herald",
                            Url = "https://www.smh.com.au/rss/feed.xml"
                        },
                        new
                        {
                            Id = 247,
                            Name = "ABC News AU",
                            Url = "https://www.abc.net.au/news/feed/51120/rss.xml"
                        },
                        new
                        {
                            Id = 248,
                            Name = "Phys.org (Science & Tech)",
                            Url = "https://phys.org/rss-feed/"
                        },
                        new
                        {
                            Id = 249,
                            Name = "MedicalXpress",
                            Url = "https://medicalxpress.com/rss-feed/"
                        },
                        new
                        {
                            Id = 250,
                            Name = "TechSpot",
                            Url = "https://www.techspot.com/backend.xml"
                        },
                        new
                        {
                            Id = 251,
                            Name = "Slashdot",
                            Url = "http://rss.slashdot.org/Slashdot/slashdotMain"
                        },
                        new
                        {
                            Id = 252,
                            Name = "Krebs on Security",
                            Url = "https://krebsonsecurity.com/feed/"
                        },
                        new
                        {
                            Id = 253,
                            Name = "BleepingComputer",
                            Url = "https://www.bleepingcomputer.com/feed/"
                        },
                        new
                        {
                            Id = 254,
                            Name = "SecurityWeek",
                            Url = "https://www.securityweek.com/feed/"
                        },
                        new
                        {
                            Id = 255,
                            Name = "SC Magazine",
                            Url = "https://www.scmagazine.com/rss"
                        },
                        new
                        {
                            Id = 256,
                            Name = "MIT News - Biology and genetics",
                            Url = "https://news.mit.edu/rss/topic/biology-and-genetics"
                        },
                        new
                        {
                            Id = 257,
                            Name = "MIT News - Cancer research",
                            Url = "https://news.mit.edu/rss/topic/cancer-research"
                        },
                        new
                        {
                            Id = 258,
                            Name = "MIT News - Chemical engineering",
                            Url = "https://news.mit.edu/rss/topic/chemical-engineering"
                        },
                        new
                        {
                            Id = 259,
                            Name = "MIT News - Robotics",
                            Url = "https://news.mit.edu/topic/mitrobotics-rss.xml"
                        },
                        new
                        {
                            Id = 260,
                            Name = "Variety",
                            Url = "https://variety.com/feed/"
                        },
                        new
                        {
                            Id = 261,
                            Name = "Rolling Stone",
                            Url = "https://www.rollingstone.com/feed/"
                        },
                        new
                        {
                            Id = 262,
                            Name = "IGN",
                            Url = "https://feeds.ign.com/ign/all"
                        },
                        new
                        {
                            Id = 263,
                            Name = "Variety",
                            Url = "https://variety.com/feed/"
                        },
                        new
                        {
                            Id = 264,
                            Name = "UN Environment Programme",
                            Url = "https://www.unep.org/rss.xml"
                        },
                        new
                        {
                            Id = 265,
                            Name = "IPCC (Intergovernmental Panel on Climate Change)",
                            Url = "https://www.ipcc.ch/feed/"
                        });
                });

            modelBuilder.Entity("MyNews.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserActivity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserNewsRead", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasClickedLink")
                        .HasColumnType("bit");

                    b.Property<bool>("HasClickedTitle")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "NewsItemId");

                    b.HasIndex("NewsItemId");

                    b.ToTable("UserNewsReads");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserSectionPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SectionType")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "SectionType");

                    b.ToTable("UserSectionPreference");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserSourcePreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "SourceId");

                    b.ToTable("UserSourcePreferences");
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.HasOne("MyNews.Api.Models.Source", "Source")
                        .WithMany("NewsItems")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsTranslation", b =>
                {
                    b.HasOne("MyNews.Api.Models.NewsItem", "NewsItem")
                        .WithMany("Translations")
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserActivity", b =>
                {
                    b.HasOne("MyNews.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("MyNews.Api.Models.UserActivity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserNewsRead", b =>
                {
                    b.HasOne("MyNews.Api.Models.NewsItem", "NewsItem")
                        .WithMany("UserReads")
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyNews.Api.Models.User", "User")
                        .WithMany("NewsReads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserSectionPreference", b =>
                {
                    b.HasOne("MyNews.Api.Models.User", "User")
                        .WithMany("UserSectionPreference")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyNews.Api.Models.UserSourcePreferences", b =>
                {
                    b.HasOne("MyNews.Api.Models.User", "User")
                        .WithMany("UserSourcePreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("UserReads");
                });

            modelBuilder.Entity("MyNews.Api.Models.Source", b =>
                {
                    b.Navigation("NewsItems");
                });

            modelBuilder.Entity("MyNews.Api.Models.User", b =>
                {
                    b.Navigation("NewsReads");

                    b.Navigation("UserSectionPreference");

                    b.Navigation("UserSourcePreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
