// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNews.Api.Data;

#nullable disable

namespace MyNews.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyNews.Api.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 8, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Source = "System",
                            Title = "Welcome to MyNews!"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 8, 30, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Source = "Demo",
                            Title = "Test News 1"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 8, 20, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Source = "Demo",
                            Title = "Test News 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
